<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="claims_part2.WebForm1" Theme="" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Add Claim </title>
    <style type="text/css">
        .auto-style2 {
            margin-left: 21px;
        }
        .auto-style3 {
            margin-left: 17px;
        }
        .auto-style4 {
            margin-left: 14px;
        }
        .auto-style5 {
            margin-left: 24px;
        }
        .auto-style6 {
            margin-left: 18px;
        }
        .auto-style7 {
            margin-left: 35px;
        }
        .auto-style12 {
            margin-left: 685px;
            margin-bottom: 284px;
        }
        .auto-style13 {
            margin-left: 13px;
        }
        </style>
</head>
<body>
       
        <div style="#C0C0C0; background-color: #C0C0C0;">
    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <h1>WORK ZONE</h1>
        <li class="nav-item"><a class="nav-link" runat="server" href="~/">Home</a></li>
        <li class="nav-item"><a class="nav-link" runat="server" href="WebForm1.aspx" >Add Claim</a></li>
         <li class="nav-item"><a class="nav-link" runat="server" href="WebForm2.aspx">Manger Page</a></li>
    </ul>
</div>
    <form id="form1" runat="server" style="background-color: #C0C0C0; font-weight: bold; font-style: normal; font-size: medium; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; text-transform: uppercase;">
        <div>
            LECTURE ID:<asp:TextBox ID="LectureIDTextBox" runat="server" CssClass="auto-style2" ForeColor="#666666" Width="157px" ></asp:TextBox>
        </div>
        <div>
            LECTURE NAME:<asp:TextBox ID="LectureNameTextBox" runat="server" CssClass="auto-style3" ForeColor="#666666" Width="157px"></asp:TextBox>
        </div>

         <div>
              MODULE CODE:<asp:TextBox ID="ModuleCodeTextBox" runat="server" CssClass="auto-style6" ForeColor="#666666" Width="157px"></asp:TextBox>
        </div>

         <div>
            MODULE NAME:<asp:TextBox ID="ModuleNameTextBox" runat="server" CssClass="auto-style6" ForeColor="#666666" Width="157px" ></asp:TextBox>
        </div>
        <div>
            CELLPHONE NUMBER:<asp:TextBox ID="CellTextBox" runat="server" CssClass="auto-style4" ForeColor="#666666" TextMode="Phone" Width="157px"></asp:TextBox>
             </div>
        <div>
             HOUR:<asp:TextBox ID="HourTextBox" runat="server" CssClass="auto-style7" ForeColor="#666666" TextMode="Number" Width="157px"></asp:TextBox>
        </div>
        <div>
            EMAIL:<asp:TextBox ID="EmailTextBox" runat="server" CssClass="auto-style5" ForeColor="#666666" TextMode="Email" Width="157px"></asp:TextBox>
            </div>
        <div>
             SALARY:<asp:TextBox ID="SalaryTextBox" runat="server" CssClass="auto-style6" ForeColor="#666666" TextMode="Number" Width="157px"></asp:TextBox>
             <br />
        </div>

        
        <p>
            <asp:Label ID="Label1" runat="server" Text="SELECT FILE"></asp:Label>
            <asp:FileUpload ID="FileUpload1" runat="server" CssClass="auto-style13" />
        </p>
        <p>

        
        <asp:Button ID="BtnSave" runat="server" CssClass="auto-style4" Text="SAVE" Width="122px" OnClick="BtnSave_Click" />
        </p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="LECTURE_ID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="Black" BorderStyle="Inset" BorderWidth="2px" ShowFooter="True" ShowHeaderWhenEmpty="True">
            <Columns>
                <asp:BoundField DataField="LECTURE_ID" HeaderText="LECTURE_ID" ReadOnly="True" SortExpression="LECTURE_ID" />
                <asp:BoundField DataField="LECTURE_NAME" HeaderText="LECTURE_NAME" SortExpression="LECTURE_NAME" />
                <asp:BoundField DataField="MODULE_ID" HeaderText="MODULE_ID" SortExpression="MODULE_ID" />
                <asp:BoundField DataField="MODULE_NAME" HeaderText="MODULE_NAME" SortExpression="MODULE_NAME" />
                <asp:BoundField DataField="HOURS" HeaderText="HOURS" SortExpression="HOURS" />
                <asp:BoundField DataField="SALARY_RATE" HeaderText="SALARY_RATE" SortExpression="SALARY_RATE" />
                <asp:BoundField DataField="TOTAL_AMOUNT" HeaderText="TOTAL_AMOUNT" SortExpression="TOTAL_AMOUNT" />
            </Columns>
            <SelectedRowStyle BackColor="Silver" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [TBLLECTURECLAIM]"></asp:SqlDataSource>
        <br />
        <br />
        <asp:Button ID="BtnLogout" runat="server" BackColor="Red" BorderStyle="None" CssClass="auto-style12" Text="LOGOUT" />
    </form>
</body>
</html>
   
